//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::bookings::Entity as Bookings;
pub use super::classes::Entity as Classes;
pub use super::organizations::Entity as Organizations;
pub use super::users::Entity as Users;
