// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A user in a studio, for the backoffice roster + role management. `is_line`
 * flags LINE-authenticated accounts (whose email is a synthetic placeholder),
 * so the UI can show a LINE badge instead of that address.
 */
export type AdminUserListItem = { pid: string, name: string, email: string, role: string, is_line: boolean, };
