// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A user as returned to the operator after creating them.
 */
export type AdminUser = { pid: string, name: string, email: string, role: string, };
