// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A studio as the operator sees it — includes the `public_id` register token
 * so the admin can hand out `/register/<public_id>` links.
 */
export type AdminOrganization = { id: number, name: string, timezone: string, public_id: string, };
