// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One section of a studio's customizable page. Tagged by `type`, so the
 * frontend sees a discriminated union it can render per block kind.
 */
export type Block = { "type": "hero", heading: string, subheading: string, } | { "type": "about", text: string, } | { "type": "gallery", images: Array<string>, };
