// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TeacherIntro } from "./TeacherIntro";

/**
 * One section of a studio's customizable page. Tagged by `type`, so the
 * frontend sees a discriminated union it can render per block kind.
 */
export type Block = { "type": "hero", heading: string, subheading: string, 
/**
 * Optional background image URL (uploaded via `/api/studio/uploads`).
 * Older stored heroes without this field deserialize to `None`.
 */
image: string | null, } | { "type": "about", text: string, } | { "type": "gallery", images: Array<string>, } | { "type": "schedule", heading: string, } | { "type": "teachers", heading: string, members: Array<TeacherIntro>, };
