// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Class } from "./Class";

/**
 * A booking as returned to the person who made it. The booked `class` is
 * embedded so "my bookings" renders without a second round-trip; `class_id`
 * is kept flat for convenience.
 */
export type Booking = { id: number, class_id: number, 
/**
 * `pending` until the (mock) payment succeeds, then `paid`.
 */
payment_status: string, created_at: string, class: Class, };
