// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The wire shape of a class session. `starts_at` is an RFC 3339 string (same
 * policy as the timestamps in [`crate::dtos::organizations::Organization`]).
 */
export type Class = { id: number, organization_id: number, title: string, instructor: string, starts_at: string, duration_minutes: number, capacity: number, created_at: string, updated_at: string, };
