// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body for creating a class. The owning studio is implicit — always the
 * authenticated user's — so it is not part of the request. `starts_at` is
 * parsed from RFC 3339 in the controller.
 */
export type CreateClassParams = { title: string, instructor: string, starts_at: string, duration_minutes: number, capacity: number, price: number, };
