// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body for making a booking. The booker is the authenticated user (from the
 * JWT), so only the target class is supplied.
 */
export type CreateBookingParams = { class_id: number, };
