// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body for creating a studio from the backoffice.
 */
export type CreateOrganizationParams = { name: string, timezone: string, };
