// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body for minting a teacher (staff) account for a studio.
 */
export type CreateStaffParams = { organization_id: number, name: string, email: string, password: string, };
