// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The wire shape of an organization (a yoga studio / tenant). Timestamps are
 * RFC 3339 strings so the JSON contract stays obvious and the frontend gets a
 * plain `string` rather than a chrono-specific type.
 */
export type Organization = { id: number, name: string, timezone: string, 
/**
 * The studio's public token — its `/studio/<token>` page and
 * `/register/<token>` link. A user only ever sees their own studio here.
 */
public_id: string, created_at: string, updated_at: string, };
