// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A class as shown on a studio's *public* page — no ids or org internals, just
 * what a prospective member needs to decide to sign up.
 */
export type PublicClass = { title: string, instructor: string, starts_at: string, duration_minutes: number, price: number, spots_left: number, photo_url: string | null, };
