// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The only studio data exposed to an *unauthenticated* visitor on the
 * per-studio register page: just the name, to show "Join ⟨name⟩". The numeric
 * id never leaves the server (registration uses the URL token), and no
 * timezone/timestamps/member/class data leaks.
 */
export type PublicOrganization = { name: string, 
/**
 * The studio's LINE LIFF id if it has enabled LINE login, else an empty
 * string. Public because the LIFF client needs it to initialise; the
 * Channel ID (used server-side to verify tokens) is never exposed here.
 */
liff_id: string, };
