// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in a class's roster, as a teacher sees it: which member holds
 * which kind of spot, and whether they've paid.
 */
export type RosterEntry = { name: string, email: string, status: string, payment_status: string, };
