// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body for changing a user's role from the backoffice (student ↔ teacher).
 */
export type SetRoleParams = { role: string, };
