// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A studio's LINE login settings, shown/edited by the studio's own staff
 * (also the PUT body). Both empty when LINE isn't set up. Unlike the public
 * studio payload, this includes the Channel ID — it is only ever returned to
 * the studio's own authenticated staff.
 */
export type StudioLineSettings = { liff_id: string, channel_id: string, };
