// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Block } from "./Block";

/**
 * A studio's page: its name plus the ordered blocks that render it.
 */
export type StudioPage = { name: string, blocks: Array<Block>, };
