// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One teacher shown in a `Teachers` block. Everything but the name is optional
 * (blank when unset), and every field has `#[serde(default)]` so partial
 * entries and older stored blocks deserialize cleanly.
 */
export type TeacherIntro = { name: string, 
/**
 * Uploaded photo URL (via `/api/studio/uploads`).
 */
photo: string | null, 
/**
 * Speciality or title, e.g. "陰瑜伽 · 10 年經驗".
 */
title: string, bio: string, instagram: string, website: string, };
