// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body for a full replacement (PUT) of a class. The owning studio is fixed at
 * creation, so it is not part of the update.
 */
export type UpdateClassParams = { title: string, instructor: string, starts_at: string, duration_minutes: number, capacity: number, price: number, };
