// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Block } from "./Block";

/**
 * Body for replacing a studio's page.
 */
export type UpdatePageParams = { blocks: Array<Block>, };
