// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of uploading an image for a studio page (e.g. a gallery photo): a
 * public URL the block can reference.
 */
export type UploadedFile = { url: string, };
